### ISSUE TITLE
Potential to use pure bash instead of shelling out to nc

### ISSUE THREAD

**Issue by fuzzy** [EddySchauHai/bashttp#1]
Bash has native socket redirection. "Echo and read, is all you need".

From: https://tldp.org/LDP/abs/html/devref1.html

```
bash$ exec 5<>/dev/tcp/www.net.cn/80
bash$ echo -e "GET / HTTP/1.0\n" >&5
bash$ cat <&5
```

**Comment by EddySchauHai** [comment]
This is really cool! I'll check it out, thanks! (This was my original goal)
